title:              Hello My Name is Collin
email:              wisser24910@gmail.com
description:        And This is my Portfolio website
author:             Collin Wisser
baseurl:            /
url:                "https://collin24910.github.io"

# Social Profiles
twitter_username:   Collinwisser
github_username:    collin24910
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
